server:
  port: 8080
spring:
  kafka:
    topic:
      csv: sa-csv
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        retires: 10